In [1]:
import os
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [2]:
X = np.load("../data/X.npy")
Y = np.load("../data/Y.npy")

# Train and Validation Sets
train_X = X[:39]  # shape: (39, 3, 24)
val_X = X[39:]    # shape: (10, 3, 24)
train_Y = Y[:39]  # shape: (39, 24)
val_Y = Y[39:]    # shape: (10, 24)

# Normalize X
X_mean = np.mean(train_X, axis=0, keepdims=True)
X_std = np.std(train_X, axis=0, keepdims=True)

train_X_norm = (train_X - X_mean) / X_std
val_X_norm   = (val_X - X_mean) / X_std

print(train_X_norm[:5])

# Normalize Y
Y_mean = np.mean(train_Y, axis=0, keepdims=True)
Y_std = np.std(train_Y, axis=0, keepdims=True)

# Normalize both training and validation Y using training set statistics
train_Y_norm = (train_Y - Y_mean) / Y_std
val_Y_norm   = (val_Y - Y_mean) / Y_std


[[[ 1.96544691  1.89090018  1.63103472  1.55475405  1.57971671
    1.47559902  1.54613365  1.20877907  1.2023891   1.16062725
    0.90683138  0.36975428  0.21047131  0.50433129  0.66391452
    0.93693405  0.9550858   0.78086046  0.50445886  0.2969833
   -0.14215755 -0.38787225 -0.33649858 -0.10276504]
  [ 2.21877628  2.28797191  2.36326372  2.38857246  2.4282269
    2.39361263  2.38429869  2.37805714  2.29728787  2.19367929
    2.04724362  1.87403809  1.65201661  1.46909818  1.32787373
    1.35979494  1.29665935  1.13896049  0.92962441  0.76941787
    0.56851036  0.41031165  0.33490702  0.10594362]
  [ 2.48682813  2.38709946  2.33682649  2.19033722  2.13671521
    2.07027948  2.07932324  2.02947926  2.0293772   2.11176924
    2.16165408  2.26257333  2.34405927  2.2456411   2.09718512
    1.81197206  1.53871871  1.49888962  1.31611648  1.13080152
    0.84082187  0.61034226  0.50157048  0.39697204]]

 [[-0.03159875  0.09864043  0.48194915  0.44053271  0.01202576
   -0.15674968 -0.1650566

In [3]:
train_X_tensor = torch.tensor(train_X_norm, dtype=torch.float32)
train_Y_tensor = torch.tensor(train_Y_norm, dtype=torch.float32)
val_X_tensor   = torch.tensor(val_X_norm, dtype=torch.float32)
val_Y_tensor   = torch.tensor(val_Y_norm, dtype=torch.float32)

train_dataset = TensorDataset(train_X_tensor, train_Y_tensor)
val_dataset = TensorDataset(val_X_tensor, val_Y_tensor)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

In [4]:
# Model Definitions
latent_dim = 16
x_dim = 3 * 24
y_dim = 24

In [5]:
class Encoder(nn.Module):
    def __init__(self, x_dim, y_dim, latent_dim):
        super(Encoder, self).__init__()
        self.fc1 = nn.Linear(x_dim + y_dim, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc_mu = nn.Linear(64, latent_dim)
        self.fc_logvar = nn.Linear(64, latent_dim)
    
    def forward(self, x, y):
        combined = torch.cat([x, y], dim=1)
        h = F.relu(self.fc1(combined))
        h = F.relu(self.fc2(h))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        return mu, logvar

In [6]:
class Decoder(nn.Module):
    def __init__(self, x_dim, latent_dim, y_dim):
        super(Decoder, self).__init__()
        self.fc1 = nn.Linear(x_dim + latent_dim, 64)
        self.fc2 = nn.Linear(64, 128)
        self.fc3 = nn.Linear(128, y_dim)
    
    def forward(self, x, z):
        combined = torch.cat([x, z], dim=1)
        h = F.relu(self.fc1(combined))
        h = F.relu(self.fc2(h))
        y_recon = self.fc3(h)
        return y_recon

In [ ]:
# CVAE model: combines encoder, reparameterization, and decoder
class CVAE(nn.Module):
    def __init__(self, x_dim, y_dim, latent_dim):
        super(CVAE, self).__init__()
        self.encoder = Encoder(x_dim, y_dim, latent_dim)
        self.decoder = Decoder(x_dim, latent_dim, y_dim)
    
    def reparameterize(self, mu, logvar):
        logvar = torch.clamp(logvar, min=-10, max=10)
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std
    
    def forward(self, x, y):
        mu, logvar = self.encoder(x, y)
        z = self.reparameterize(mu, logvar)
        y_recon = self.decoder(x, z)
        return y_recon, mu, logvar

In [9]:
def loss_function(y_recon, y, mu, logvar):
    recon_loss = F.mse_loss(y_recon, y, reduction='mean')
    kl_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kl_loss

In [10]:
model = CVAE(x_dim, y_dim, latent_dim)
optimizer = optim.Adam(model.parameters(), lr=1e-3)
num_epochs = 100

In [11]:
for epoch in range(1, num_epochs + 1):
    model.train()
    train_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x = batch_x.view(batch_x.size(0), -1)
        optimizer.zero_grad()
        y_recon, mu, logvar = model(batch_x, batch_y)
        loss = loss_function(y_recon, batch_y, mu, logvar)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * batch_x.size(0)
    train_loss /= len(train_dataset)
    
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in val_loader:
            batch_x = batch_x.view(batch_x.size(0), -1)
            y_recon, mu, logvar = model(batch_x, batch_y)
            loss = loss_function(y_recon, batch_y, mu, logvar)
            val_loss += loss.item() * batch_x.size(0)
    val_loss /= len(val_dataset)
    
    print(f"Epoch {epoch}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")


Epoch 1/100, Train Loss: 1.0214, Val Loss: 0.7975
Epoch 2/100, Train Loss: 0.9851, Val Loss: 0.7752
Epoch 3/100, Train Loss: 0.9668, Val Loss: 0.7712
Epoch 4/100, Train Loss: 0.9379, Val Loss: 0.7646
Epoch 5/100, Train Loss: 0.9120, Val Loss: 0.7651
Epoch 6/100, Train Loss: 0.8966, Val Loss: 0.7848
Epoch 7/100, Train Loss: 0.8745, Val Loss: 0.7843
Epoch 8/100, Train Loss: 0.8553, Val Loss: 0.8163
Epoch 9/100, Train Loss: 0.8351, Val Loss: 0.8395
Epoch 10/100, Train Loss: 0.8364, Val Loss: 0.8576
Epoch 11/100, Train Loss: 0.7931, Val Loss: 0.8759
Epoch 12/100, Train Loss: 0.7793, Val Loss: 0.9217
Epoch 13/100, Train Loss: 0.7540, Val Loss: 0.9736
Epoch 14/100, Train Loss: 0.7229, Val Loss: 0.9639
Epoch 15/100, Train Loss: 0.7294, Val Loss: 0.9857
Epoch 16/100, Train Loss: 0.6973, Val Loss: 1.0556
Epoch 17/100, Train Loss: 0.6558, Val Loss: 1.1349
Epoch 18/100, Train Loss: 0.6179, Val Loss: 1.0576
Epoch 19/100, Train Loss: 0.6052, Val Loss: 1.1148
Epoch 20/100, Train Loss: 0.5874, Val Lo

In [26]:
model.eval()
with torch.no_grad():
    sample_x, sample_y = next(iter(val_loader))
    sample_x = sample_x.view(sample_x.size(0), -1)
    y_recon, _, _ = model(sample_x, sample_y)
    print("\nValidation Sample:")
    print("True Y:")
    print(sample_y[0])
    print("Predicted Y:")
    print(y_recon[0])


Validation Sample:
True Y:
tensor([-0.1349,  0.1399, -0.1809,  0.4955,  0.6899,  0.6104,  0.7086,  0.4167,
         0.5230, -0.7771, -0.9032, -0.8574,  0.3308, -0.4826, -0.6513, -0.4828,
        -0.5125,  0.1398,  0.4041, -0.5161,  0.6285,  0.0626, -0.0558, -0.7194])
Predicted Y:
tensor([-0.3123, -0.2754, -0.1772, -0.2586, -0.5307, -0.3385, -0.8988, -0.0713,
         0.3018, -0.1347, -0.4275, -0.4262, -0.5946, -0.6787, -0.6830, -0.9174,
        -0.9628,  0.0504, -0.0324,  0.4475,  0.7067,  0.3458,  0.1038, -0.5842])


In [31]:
pred, mu, logvar = model(sample_x, sample_y)
logvar.shape

torch.Size([8, 16])

In [33]:
model.eval()
samples = []
with torch.no_grad():
    sample_x, sample_y = next(iter(val_loader))
    sample_x = sample_x.view(sample_x.size(0), -1)
    for i in range(16):
        y_recon, _, _ = model(sample_x, sample_y)
        samples.append(y_recon[0])
samples

[tensor([-0.4619, -0.2640, -0.2640, -0.1893, -0.5627, -0.2505, -0.8770,  0.0033,
          0.4735, -0.0948, -0.3619, -0.4711, -0.4887, -0.6822, -0.7811, -0.9701,
         -0.9746,  0.0159,  0.0521,  0.5719,  0.5734,  0.3064,  0.1660, -0.6459]),
 tensor([-0.4338, -0.2508, -0.2009, -0.2078, -0.4976, -0.2022, -0.7027, -0.0884,
          0.3143, -0.1109, -0.4237, -0.4301, -0.4329, -0.6812, -0.7615, -0.7994,
         -0.9719,  0.0274, -0.0593,  0.3972,  0.4499,  0.2606,  0.1623, -0.6844]),
 tensor([-0.4433, -0.3053, -0.1905, -0.2525, -0.5136, -0.3268, -0.8877, -0.1119,
          0.4158, -0.1383, -0.4077, -0.4170, -0.5042, -0.6993, -0.7201, -0.7274,
         -0.9166,  0.0468,  0.0800,  0.4600,  0.5667,  0.1697,  0.0526, -0.5690]),
 tensor([-3.9278e-01, -1.0720e-01, -8.7175e-02, -5.2402e-02, -3.5676e-01,
         -1.9019e-01, -7.1658e-01,  9.1864e-05,  3.9540e-01,  4.6172e-02,
         -2.2574e-01, -3.9248e-01, -2.8280e-01, -4.8100e-01, -5.4001e-01,
         -6.6592e-01, -7.9293e-01, -8.5853e

In [36]:
import plotly.graph_objects as go

traces = []
for i, sample in enumerate(samples):
    traces.append({"y": sample, "name": f"Sample {i}"})

go.Figure(data=traces)